# Configure Using Gemfile 
# gem 'pg' 

default: &default
 adapter: postgresql 
 username: postgres 
 password: 123456
 pool: 5

development:
  <<: *default
  database: el_training_development 

test: 
  <<: *default 
  database: el_training_test 
   
production: 
  <<: *default 
  database: el_training_production
  username: el_training
  password: <%= ENV['EL_TRAINING_DATABASE_PASSWORD'] %>
